# -*- coding: utf-8 -*-
"""Worksheet2_2501623_RojinaGurung.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wyN4drblqYLAi0EciUo_Q-FbrvBMm2ML

Worksheet2 RojinaGurung
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

bank_path = "/content/drive/MyDrive/Technologies_of_AI/bank.csv"
medical_student_path = "/content/drive/MyDrive/Technologies_of_AI/medical_students_dataset.csv"
titanic_path = "/content/drive/MyDrive/Technologies_of_AI/Titanic-Dataset.csv"

"""3.1 Warming up Exercises

Problem 1 - Data Read, Write and Inspect:
"""

#Load and inspect bank.csv

bank_df = pd.read_csv(bank_path)

print("First 5 rows:")
display(bank_df.head())

print("\nInfo:")
bank_df.info()

# (a) Object dtype columns
object_cols = bank_df.select_dtypes(include="object").columns
print("\n(a) Object dtype columns:")
print(list(object_cols))

# (b) Unique values in those columns
print("\n(b) Unique values:")
for col in object_cols:
    print(f"\nColumn: {col}")
    print(bank_df[col].unique())

# (c) Null values
print("\n(c) Null values in each column:")
print(bank_df.isnull().sum())

#Drop object columns and save numeric data

bank_numeric_df = bank_df.drop(columns=object_cols)

print("Numeric DataFrame:")
display(bank_numeric_df.head())

# Save to CSV
bank_numeric_df.to_csv("banknumericdata.csv", index=False)
print("\nSaved as banknumericdata.csv")

#Load numeric CSV and get summary

df_num = pd.read_csv("banknumericdata.csv")

print("Info:")
df_num.info()

print("\nSummary Statistics:")
display(df_num.describe())

"""Problem 2 - Data Imputations"""

#Load medical_student.csv

medical_df = pd.read_csv(medical_student_path)

print("First 5 rows:")
display(medical_df.head())

print("\nInfo:")
medical_df.info()

print("\nMissing values:")
print(medical_df.isnull().sum())

#Impute missing values

num_cols = medical_df.select_dtypes(include=[np.number]).columns
cat_cols = medical_df.select_dtypes(include="object").columns

medical_imputed = medical_df.copy()

# Numeric = median
for col in num_cols:
    if medical_imputed[col].isnull().sum() > 0:
        med = medical_imputed[col].median()
        medical_imputed[col].fillna(med, inplace=True)
        print(f"Filled numeric column '{col}' with median = {med}")

# Categorical = mode
for col in cat_cols:
    if medical_imputed[col].isnull().sum() > 0:
        mode_val = medical_imputed[col].mode()[0]
        medical_imputed[col].fillna(mode_val, inplace=True)
        print(f"Filled categorical column '{col}' with mode = {mode_val}")

print("\nMissing values after imputation:")
print(medical_imputed.isnull().sum())

display(medical_imputed.head())

#Remove duplicates

duplicates_before = medical_imputed.duplicated().sum()
print("Duplicates before:", duplicates_before)

medical_no_dup = medical_imputed.drop_duplicates()

duplicates_after = medical_no_dup.duplicated().sum()
print("Duplicates after:", duplicates_after)

print("\nShape before:", medical_imputed.shape)
print("Shape after: ", medical_no_dup.shape)

"""3.2 Exercises"""

#Titanic Setup
titanic_df = pd.read_csv(titanic_path)

print("First 5 rows:")
display(titanic_df.head())

print("\nInfo:")
titanic_df.info()

"""Problem 1"""

cols_needed = ["Name", "Pclass", "Sex", "Age", "Fare", "Survived"]
subset_df = titanic_df[cols_needed]

first_class = subset_df[subset_df["Pclass"] == 1]

print("First 5 rows of first-class passengers:")
display(first_class.head())

print("\nFare Statistics:")
print("Mean:", first_class["Fare"].mean())
print("Median:", first_class["Fare"].median())
print("Max:", first_class["Fare"].max())
print("Min:", first_class["Fare"].min())

"""Problem 2"""

print("Null Age values:", first_class["Age"].isnull().sum())

first_class_no_null_age = first_class.dropna(subset=["Age"])

print("\nBefore:", first_class.shape)
print("After:", first_class_no_null_age.shape)

display(first_class_no_null_age.head())

"""Problem 3"""

embarked_dummies = pd.get_dummies(titanic_df["Embarked"], prefix="Embarked")

titanic_encoded = pd.concat([titanic_df, embarked_dummies], axis=1)
titanic_encoded.drop(columns=["Embarked"], inplace=True)

print("After encoding:")
display(titanic_encoded.head())

"""Problem 4"""

survival_by_gender = titanic_df.groupby("Sex")["Survived"].mean()
print(survival_by_gender)

plt.figure(figsize=(6,4))
survival_by_gender.plot(kind="bar")
plt.title("Mean Survival Rate by Gender")
plt.xlabel("Gender")
plt.ylabel("Survival Rate")
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.show()

"""Problem 5"""

titanic_no_null = titanic_df.dropna(subset=["Embarked"])

survival_se = (
    titanic_no_null.groupby(["Sex", "Embarked"])["Survived"]
    .mean()
    .unstack("Embarked")
)

print("Survival table:")
display(survival_se)

survival_se.plot(kind="bar", figsize=(8,5))
plt.title("Survival by Gender and Embarkation Point")
plt.xlabel("Gender")
plt.ylabel("Survival Rate")
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.show()

"""Problem 6"""

df_age = titanic_df.dropna(subset=["Age"]).copy()
df_age["AgeGroup"] = pd.qcut(df_age["Age"], 5)

surv_age_class = (
    df_age.groupby(["AgeGroup", "Pclass"])["Survived"]
    .mean()
    .unstack("Pclass")
)

print("Survival table:")
display(surv_age_class)

plt.figure(figsize=(8,6))
plt.imshow(surv_age_class, aspect="auto")
plt.colorbar(label="Survival Rate")

plt.xticks(range(3), surv_age_class.columns)
plt.yticks(range(len(surv_age_class.index)), surv_age_class.index)

plt.title("Survival by Age Group and Passenger Class")
plt.xlabel("Pclass")
plt.ylabel("Age Group")
plt.show()